version: "3.3"

services:

  postgres-server:
    image: postgres:11.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: vitortcc
      TZ: America/Recife
    volumes:
      - pgdata:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix-server:new
    #image: zabbix/zabbix-server-pgsql:ubuntu-4.4-latest
    ports:
      - "10051:10051"
      - "10050:10050"
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: vitortcc        
      ZBX_STARTPOLLERS: 2 #Quantidade de processos pré-alocados dos pollers 
      ZBX_STARTPINGERS: 2 #Quantidade de processos pré-alocados dos ICMP pingers - 1
      ZBX_STARTTRAPPERS: 2
      ZBX_STARTPOLLERSUNREACHABLE: 2 #Quantidade de processos pré-alocados dos pollers de hosts indisponíveis - 1
      ZBX_STARTDISCOVERERS: 15 #qtd de processo pré-alocados para o discovery - 1
      ZBX_TIMEOUT: 20 #tempo máximo para o zbx aguardar um dado do agente
      ZBX_SENDERFREQUENCY: 30 #tempo para o enviar alertas pendentes - 30
      ZBX_STARTDBSYNCERS: 2 #Quantidade de processos pré-alocados dos DB Syncers -4
      ZBX_CACHESIZE: 500M
      ZBX_HISTORYCACHESIZE: 500M
      ZBX_TRENDCACHESIZE: 500M
      ZBX_HOUSEKEEPINGFREQUENCY: 24 #Intervalo entre execuções do processo de limpeza de dados (housekeeping) (em horas) - 6 
      ZBX_DEBUGLEVEL: 3
      TZ: America/Recife
    depends_on:
      - postgres-server
    volumes:
      - ./alertscripts:/usr/lib/zabbix/alertscripts
      - ./externalscripts:/usr/lib/zabbix/externalscripts

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-4.4-latest
    ports:
      - "8080:80"
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: vitortcc
      ZBX_SERVER_NAME: "vitortcc" 
      TZ: America/Recife
      PHP_TZ: America/Recife
  grafana:
    image: grafana/grafana:6.6.2-ubuntu
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,michaeldmoore-multistat-panel,grafana-polystat-panel,grafana-worldmap-panel,alexanderzobnin-zabbix-app  
      GF_SECURITY_ADMIN_PASSWORD: vitortcc
      GF_USERS_DEFAULT_THEME: dark
      TZ: America/Recife
    volumes:
      - grafana:/var/lib/grafana


volumes:
  pgdata:
  alertscripts:
  externalscripts:
  grafana:
